[scripts]
build = "node build.js"
test = "node test.js"
start = "ts-node index.ts i"

[dependencies]
express = "4.17.1"
mongodb = "4.0.0"
imagizer-javascript = "1.9.1"

[devDependncies]
typescript = "4.6.4"
