[mongodb]
mongodb = "4.6.0"
bson = "^4.6.3"
buffer = "^5.6.0"
denque = "^2.0.1"
mongodb-connection-string-url = "^2.5.2"
"@types/whatwg-url" = "^8.2.1"
whatwg-url = "^11.0.0"
socks = "^2.6.2"
ip = "^1.1.5"
smart-buffer = "^4.2.0"
saslprep = "^1.0.3"
sparse-bitfield = "^3.0.3"

[fs-extra]
fs-extra = "10.1.0"
graceful-fs = "^4.1.6"
jsonfile = "^6.0.1"
universalify = "^2.0.0"
