[snake-case]
snake-case = "3.0.4"
dot-case = "^3.0.4"
no-case = "^3.0.4"
lower-case = "^2.0.2"
tslib = "^2.0.3"

[express]
express = "4.18.1"
accepts = "~1.3.8"
mime-types = "~2.1.24"
negotiator = "0.6.3"
array-flatten = "1.1.1"
body-parser = "1.20.0"
bytes = "3.1.2"
content-type = "~1.0.4"
debug = "2.6.9"
depd = "2.0.0"
destroy = "1.2.0"
http-errors = "2.0.0"
iconv-lite = "0.4.24"
on-finished = "2.4.1"
qs = "6.10.3"
raw-body = "2.5.1"
type-is = "~1.6.18"
unpipe = "~1.0.0"
content-disposition = "0.5.4"
safe-buffer = "5.2.1"
cookie = "0.5.0"
cookie-signature = "1.0.6"
ms = "2.1.3"
encodeurl = "~1.0.2"
escape-html = "~1.0.3"
etag = "~1.8.1"
finalhandler = "1.2.0"
parseurl = "~1.3.3"
statuses = "2.0.1"
fresh = "0.5.2"
inherits = "2.0.4"
setprototypeof = "1.2.0"
toidentifier = "1.0.1"
merge-descriptors = "1.0.1"
methods = "~1.1.2"
ee-first = "1.1.1"
path-to-regexp = "0.1.7"
proxy-addr = "~2.0.7"
forwarded = "0.2.0"
"ipaddr.js" = "1.9.1"
side-channel = "^1.0.4"
range-parser = "~1.2.1"
send = "0.18.0"
mime = "1.6.0"
serve-static = "1.15.0"
media-typer = "0.3.0"
utils-merge = "1.0.1"
vary = "~1.1.2"

[mongodb]
mongodb = "4.6.0"
bson = "^4.6.3"
buffer = "^5.6.0"
denque = "^2.0.1"
mongodb-connection-string-url = "^2.5.2"
"@types/whatwg-url" = "^8.2.1"
whatwg-url = "^11.0.0"
socks = "^2.6.2"
ip = "^1.1.5"
smart-buffer = "^4.2.0"
saslprep = "^1.0.3"
sparse-bitfield = "^3.0.3"

[fs-extra]
fs-extra = "10.1.0"
graceful-fs = "^4.1.6"
jsonfile = "^6.0.1"
universalify = "^2.0.0"
